apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: todo
profiles:
  - name: local
    activation:
      - kubeContext: minikube
    build:
      tagPolicy:
        sha256: {}
      artifacts:
        - image: johnnyhuy/todo-frontend
          context: apps/todo-frontend
          docker:
            cliFlags: 
              - --platform
              - linux/amd64
          sync:
            manual:
              - src: 'src/**/*'
                dest: .
              - src: 'public/**/*'
                dest: .
              - src: '*.html'
                dest: .
              - src: '*.js'
                dest: .
              - src: '*.ts'
                dest: .

        - image: johnnyhuy/todo-backend
          context: apps/todo-backend
          docker:
            cliFlags: 
              - --platform
              - linux/amd64
          sync:
            manual:
              - src: 'src/**/*'
                dest: .
    deploy:
      helm:
        hooks:
          before:
            - host:
                command: ["sh", "-c", "./bin/helm-repo-add.sh"]
                os: [darwin, linux]
        releases:
          - name: todo
            chartPath: charts/todo
            wait: true
            createNamespace: true
            namespace: default

    portForward:
      - resourceType: service
        resourceName: todo-frontend
        namespace: default
        port: 3000

      - resourceType: service
        resourceName: todo-backend
        namespace: default
        port: 3001
