apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: kube-system
profiles:
  - name: local
    activation:
      - kubeContext: minikube
    deploy:
      helm:
        hooks:
          before:
            - host:
                command: ["sh", "-c", "./bin/helm-repo-add.sh"]
                os: [darwin, linux]
        releases:
          - name: kube-system
            chartPath: charts/kube-system
            namespace: kube-system

  - name: prod
    deploy:
      helm:
        hooks:
          before:
            - host:
                command: ["sh", "-c", "./bin/helm-repo-add.sh"]
                os: [darwin, linux]
        releases:
          - name: kube-system
            chartPath: charts/kube-system
            namespace: kube-system
---

apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: todo
profiles:
  - name: local
    activation:
      - kubeContext: minikube
    build:
      tagPolicy:
        sha256: {}
      artifacts:
        - image: johnnyhuy/todo-frontend
          context: apps/todo-frontend
          docker:
            dockerfile: dev.Dockerfile
            cliFlags: 
              - --platform
              - linux/amd64
          sync:
            manual:
              - src: 'src/**/*'
                dest: .
              - src: 'public/**/*'
                dest: .
              - src: '*.html'
                dest: .
              - src: '*.js'
                dest: .
              - src: '*.ts'
                dest: .

        - image: johnnyhuy/todo-backend
          context: apps/todo-backend
          docker:
            dockerfile: dev.Dockerfile
            cliFlags: 
              - --platform
              - linux/amd64
          sync:
            manual:
              - src: 'src/**/*'
                dest: .
    deploy:
      helm:
        hooks:
          before:
            - host:
                command: ["sh", "-c", "./bin/helm-repo-add.sh"]
                os: [darwin, linux]
        releases:
          - name: todo
            chartPath: charts/todo
            namespace: default
            artifactOverrides:
              frontend.image: johnnyhuy/todo-frontend
              backend.image: johnnyhuy/todo-backend
            imageStrategy:
              helm: {}

    portForward:
      - resourceType: service
        resourceName: todo-frontend
        namespace: default
        port: 8080

      - resourceType: service
        resourceName: todo-backend
        namespace: default
        port: 8081

  - name: prod
    activation:
      - kubeContext: minikube
    build:
      tagPolicy:
        sha256: {}
      artifacts:
        - image: johnnyhuy/todo-frontend
          context: apps/todo-frontend
          docker:
            dockerfile: prod.Dockerfile
            cliFlags: 
              - --platform
              - linux/amd64

        - image: johnnyhuy/todo-backend
          context: apps/todo-backend
          docker:
            dockerfile: prod.Dockerfile
            cliFlags: 
              - --platform
              - linux/amd64
    deploy:
      helm:
        hooks:
          before:
            - host:
                command: ["sh", "-c", "./bin/helm-repo-add.sh"]
                os: [darwin, linux]
        releases:
          - name: todo
            chartPath: charts/todo
            namespace: default
            valuesFiles:
              - charts/todo/values.prod.yaml
            artifactOverrides:
              frontend.image: johnnyhuy/todo-frontend
              backend.image: johnnyhuy/todo-backend
            imageStrategy:
              helm: {}
