apiVersion: v1
kind: Service
metadata:
  name: minikube-prometheus-statsd-exporter
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: statsd-udp
      protocol: UDP
      port: {{ index .Values "prometheus-statsd-exporter" "statsd" "udpPort" }}
      targetPort: statsd-udp
  selector:
    app.kubernetes.io/instance: {{ .Release.Namespace }}
    app.kubernetes.io/name: prometheus-statsd-exporter
  type: LoadBalancer
---

apiVersion: v1
kind: Service
metadata:
  name: minikube-grafana
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http-web
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app.kubernetes.io/instance: {{ .Release.Namespace }}
    app.kubernetes.io/name: grafana
  type: LoadBalancer
---

apiVersion: v1
kind: Service
metadata:
  name: minikube-prometheus-alertmanager
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http-web
      protocol: TCP
      port: 9093
      targetPort: 9093
  selector:
    alertmanager: prometheus-alertmanager
    app.kubernetes.io/name: alertmanager
  type: LoadBalancer
---

apiVersion: v1
kind: Service
metadata:
  name: minikube-prometheus-prometheus
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http-web
      protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30470
  selector:
    app.kubernetes.io/name: prometheus
    prometheus: prometheus-prometheus
  type: LoadBalancer
