apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      kubernetes.io/name: todo-frontend
  template:
    metadata:
      labels:
        kubernetes.io/name: todo-frontend
    spec:
      containers:
        - name: todo-frontend
          image: johnnyhuy/todo-frontend:latest
          pullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      kubernetes.io/name: todo-backend
  template:
    metadata:
      labels:
        kubernetes.io/name: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: johnnyhuy/todo-frontend:latest
          pullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
