apiVersion: v1
kind: Service
metadata:
  name: minikube-kubeinvaders
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.kubeinvaders.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: kubeinvaders
    app.kubernetes.io/instance: {{ .Release.Name }}
