apiVersion: v1
kind: Service
metadata:
  name: todo-frontend
spec:
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    kubernetes.io/name: todo-frontend
---

apiVersion: v1
kind: Service
metadata:
  name: todo-backend
spec:
  ports:
    - port: 3001
      targetPort: http
      protocol: TCP
      name: http
  selector:
    kubernetes.io/name: todo-backend
