apiVersion: v1
kind: Service
metadata:
  name: minikube-todo-frontend
spec:
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    kubernetes.io/name: todo-frontend
---

apiVersion: v1
kind: Service
metadata:
  name: todo-frontend
spec:
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    kubernetes.io/name: todo-frontend
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      kubernetes.io/name: todo-frontend
  template:
    metadata:
      labels:
        kubernetes.io/name: todo-frontend
    spec:
      containers:
        - name: todo-frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
